### ISSUE TITLE
Confused,error with "directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/PrivateFrameworks"

### ISSUE THREAD

**Issue by KittenYang** [xindawndev/RecordMyScreen-iOS10#1]
I got this error:`directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/PrivateFrameworks`. No way to fix it.

already fixed

**Comment by xindawndev** [comment]
already fixed.

2016-04-10 2:21 GMT+08:00 Qitao Yang notifications@github.com:

**Comment by KittenYang** [comment]
@xindawndev  Why it just record audio,not screen video?

**Comment by xindawndev** [comment]
Tap Airplay,Select XBMC-GAMEBOX(XinDawn), and finally if you see the option
turn on Mirroring'

2016-04-10 14:25 GMT+08:00 Qitao Yang notifications@github.com:
