### ISSUE TITLE
你好 我想你应该是懂中文的.

### ISSUE THREAD

**Issue by LenovoLRSH** [xindawndev/RecordMyScreen-iOS10#2]
验证码过期了.你们这个是怎么卖的啊?

**Comment by xindawndev** [comment]
你是公司还是个人开发者？告诉我测试机器的ECID。用itunes查看？

2016-05-05 21:31 GMT+08:00 chjxz notifications@github.com:

**Comment by LenovoLRSH** [comment]
个人开发者
你们这个怎么收费的啊?

**Comment by LenovoLRSH** [comment]
D741110298826

**Comment by xindawndev** [comment]
你这是序列号，不是ECID

2016-05-06 10:31 GMT+08:00 chjxz notifications@github.com:

**Comment by LenovoLRSH** [comment]
这个是ecid 你是不是要udid啊>?

**Comment by xindawndev** [comment]
ecid是数字开头的

2016-05-06 11:11 GMT+08:00 chjxz notifications@github.com:

**Comment by LenovoLRSH** [comment]
加个qq?200864334

**Comment by xindawndev** [comment]
fixes #2

**Comment by xindawndev** [comment]
close #2
