### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by chandu8034** [xindawndev/RecordMyScreen-iOS10#21]
I downloaded the source code from the below link:
https://github.com/xindawndev/RecordMyScreen-iOS10

I opened the xcodeproj in my Mac (V 10.11.6) using xcode (v8.2)

I am quite a new bee to xcode and tried to compile it. But I am getting Linker errors as below:

Undefined symbols for architecture x86_64:
      "_XinDawn_StopMediaServer", referenced from:
            -[CSScreenRecorder stopRecrodingScreen] in CSScreenRecorder.o

Similar error is observed for "_X_inDawn_StartMediaServer" too.

Is there anything else I need to include along with xcode project? Please guide me how to work this on Simulator as well as real time phone as I am doing experiments of my own. I have a iphone 5s non jail broken phone as the destination,.

Many thanks for your help

**Comment by xindawndev** [comment]
The SDK only support the arm64 and armv7

2016-12-21 14:58 GMT+08:00 chandu8034 <notifications@github.com>:

**Comment by chandu8034** [comment]
how do i make it work on my xcode? Can you please let me know what needs to be done?

As I said, I am quite unfamiliar with the environment. This app really suits my requirement and hance I want to make it work.

BTW, I don't understand you above statement. Does this mean iphone 5s is not armv7 and arm64 supportable?

**Comment by xindawndev** [comment]
It can work on iPhone 5S

2016-12-21 15:07 GMT+08:00 chandu8034 <notifications@github.com>:

**Comment by chandu8034** [comment]
Then can u tell me what am I doing wrong?

**Comment by chandu8034** [comment]
also if u r saying it supports only arm architecture, why am I getting linker errors related to x86_64? Seems like I am  missing some project settings..am I not?

**Comment by xindawndev** [comment]
Please tell me your email address

2016-12-21 15:14 GMT+08:00 chandu8034 <notifications@github.com>:

**Comment by chandu8034** [comment]
gbhanuchandra@gmail.com

**Comment by chandu8034** [comment]
let me know if you are able to see the email address as I am unsure of what is the policy being followed in github..

**Comment by chandu8034** [comment]
I was able to resolve the issues with your help. Thanks a lot!!!
