### ISSUE TITLE
Does not build/run on iOS simulator or iPad 3

### ISSUE THREAD

**Issue by sidneys** [xindawndev/RecordMyScreen-iOS10#4]
Hi,

the application does not build/run for iOS simulator or iPad 3 targets, as the underlying libs(libairplaysdk-1.a, libairplaysdk-2.a) only contain the arm64 slice. However, xindawn.com states that it should be compatible with ARMv7/ARM64/i386/x86_64 architectures.

**Comment by xindawndev** [comment]
The commercial version of SDK is compatible with ARMv7/ARM64/i386/x86_64
architectures.

2016-05-12 21:21 GMT+08:00 Sidney notifications@github.com:
