### ISSUE TITLE
请问这个sdk使用上有限制吗？

### ISSUE THREAD

**Issue by yaveymao** [xindawndev/RecordMyScreen-iOS10#42]
由于项目没有开源，所以关心几个个问题：
1、这个sdk使用上有没有限制，是否按时间限制使用？或者按次数限制使用？
2、ios11马上要出来了，贵公司是否持续更新？
3、能否购买完整的包含源码的sdk？

**Comment by xindawndev** [comment]
1.请发邮件到xindawndev@gmail.com
2.QQ：3093027760

yaveymao <notifications@github.com>于2017年7月28日 周五下午7:09写道：
