### ISSUE TITLE
iOS11 crash 

### ISSUE THREAD

**Issue by AMKaffiOS** [xindawndev/RecordMyScreen-iOS10#51]
NSString *videoPath = fileName;
    NSString *audioPath = audioOutPath;
    
    NSURL *videoURL = [NSURL fileURLWithPath:videoPath];

videoPath is nil

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

**Comment by xindawndev** [comment]
the ios 11 device doesn't automatically connect to airplay,
     swipe up from the bottom of you screen to access control center,
     and tap the name of the XBMC-GAMEBOX(XinDawn), Recording Screen will start.



2018-07-13 16:26 GMT+08:00 AM_iOS <notifications@github.com>:
