### ISSUE TITLE
can not build in iOS7

### ISSUE THREAD

**Issue by fenglinxiu** [xindawndev/RecordMyScreen-iOS10#6]
I can build and run this project on iOS8 & iOS9 phone successfully. But I get a failure on iOS7 phone building it. 
The flowing is the error note. I can not make it. Expect your reply. Thanks.

  "_XinDawn_StopMediaServer", referenced from:
      -[CSScreenRecorder stopRecordingScreen] in CSScreenRecorder.o
  "_XinDawn_StartMediaServer", referenced from:
      -[CSScreenRecorder startRecordingScreen] in CSScreenRecorder.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xindawndev** [comment]
fixed

**Comment by NeelVegda** [comment]
i have a same issue but in iOS10.

Undefined symbols for architecture x86_64:
  "_XinDawn_StopMediaServer", referenced from:
      -[CSScreenRecorder stopRecordingScreen] in CSScreenRecorder.o
  "_XinDawn_StartMediaServer", referenced from:
      -[CSScreenRecorder startRecordingScreen] in CSScreenRecorder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xindawndev** [comment]
only supports armv7 and arm64

2017-05-04 20:44 GMT+08:00 Neel Vegda <notifications@github.com>:
